2021-06-07 14:34:56,857 - youtrack.py: get_issue_by_project - ERROR - HTTPConnectionPool(host='space.techstar.com.cn', port=8081): Max retries exceeded with url: /api/admin/projects/17CJY003/issues?fields=id,summary,customFields(id,name,value(fullName,id,minutes,name,presentation,text))&$skip=0&$top=500 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002162D68C748>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-06-07 14:36:12,118 - youtrack.py: get_issue_by_project - ERROR - HTTPConnectionPool(host='space.techstar.com.cn', port=8081): Max retries exceeded with url: /api/admin/projects/17CJY003/issues?fields=id,summary,customFields(id,name,value(fullName,id,minutes,name,presentation,text))&$skip=0&$top=500 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A66FE1B788>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-06-08 13:52:27,131 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 13:57:18,738 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 13:58:46,869 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 16:11:22,708 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 16:14:09,627 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 16:15:42,427 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 16:33:01,253 - youtrack.py: async_issue_by_project - INFO - 收到数据条数：2753
2021-06-08 17:25:39,478 - youtrack.py: get_workItems - ERROR - Failed to parse: http://space.techstar.com.cn:8081api/workItems?fields=created,duration(presentation,minutes),author(name),creator(name),date,id,text,type,updated
